pipeline {
    agent any

    tools {
        maven 'Maven 3.8.8'   // This name must match Jenkins Global Tool Config
        jdk 'Java 17'         // Same here
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/MalakGhazy/JFreeChart-UnitTesting.git', branch: 'main'
            }
        }

        stage('Build and Test') {
            steps {
               dir('JFreeChart') {
                    sh 'mvn clean test'
               }
            }
        }
        post {
            always {
                junit 'target/surefire-reports/*.xml'
            }
        }
}